import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Header } from "@/components/Header";
import { LeftBar } from "@/components/LeftBar";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={GeistSans.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div
              id="body-wrapper"
              className="flex text-left flex-row flex-wrap w-full h-full bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] background-animate
                from-pink-100
                via-red-100
                to-yellow-300
                dark:from-slate-950
                dark:via-cyan-950
                dark:to-slate-950
              "
              >

              <Header />

              <div id="content" className="flex flex-row w-full">
                <LeftBar />

                <div id="main" className="flex flex-col w-10/12 pl-52 pt-52">
                  <Suspense fallback={<div>Loading...</div>}> 
                    {children}
                  </Suspense>
                </div>
              </div>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
