import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ModeToggle } from "@/components/ModeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={GeistSans.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div
              id="body-wrapper"
              className="flex flex-row flex-wrap w-full h-screen bg-gradient-to-r  background-animate
                from-pink-100
                via-red-100
                to-yellow-300
                dark:from-slate-800
                dark:via-slate-700
                dark:to-slate-900
              ">
              <div
                id="header"
                className="flex w-full justify-end  border-b-4 dark:border-slate-50 border-slate-800"
              >
                <ModeToggle />
              </div>

              {children}
            </div>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
